--- 

name: Python Notebooks Linting
on:
  push:
    branches:
      - '**'
      
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
         python -m pip install --upgrade pip
            pip install pylint
            pip install umsgpack
            pip install cryptography
            pip install pylint-fail-under
      - name: Analysing the code with pylint
        run: find . -name '*.py' -print -exec pylint {} \;
      - name: Lints each python file and fails if pylint score is less than 6.0
        run: |
              for file in $(find -name '*.py')
              do
                pylint "$file" --fail-under=7.0;
              done